# Generated by Django 2.2.4 on 2020-01-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='phone',
            field=models.IntegerField(max_length=10, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='zipcode',
            field=models.IntegerField(max_length=10, verbose_name='zipcode'),
        ),
    ]
