# Generated by Django 2.2.4 on 2020-01-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m1', '0003_auto_20200130_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='items_json',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='username',
        ),
        migrations.AlterField(
            model_name='orders',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='orders',
            name='hour',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='lbox',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='mbox',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='minutes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='orders',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='pickup_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='sbox',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='zipcode',
            field=models.IntegerField(),
        ),
    ]
